python_tests(
  name = 'http_observer',
  sources = ['test_*.py'],
  environment = 'local',
  dependencies = [
    'src/main/python/apache/thermos/observer:observer',
    'src/main/python:all_src',
  ],
)
