# src/test/python/apache/aurora/executor/BUILD

python_tests(
  name = 'executor',
  sources = ['test_*.py'],
  environment = 'local',
  dependencies = [
    'src/main/python/apache/aurora/executor:executor',
    'src/main/python:all_src',
  ],
)
